/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.UsuarioController;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author ivald
 */
public class TelaCadastro extends javax.swing.JFrame {

    /**
     * Creates new form TelaCadastro
     */
    public TelaCadastro() {
        initComponents();
        getContentPane().setBackground(Color.BLACK);
        setLocationRelativeTo(null);
    }
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelSpotifei2 = new javax.swing.JLabel();
        jLabelEmailCadastro = new javax.swing.JLabel();
        jLabelSenhaCadastro = new javax.swing.JLabel();
        campoEmailCadastro = new javax.swing.JTextField();
        campoSenhaCadastro = new javax.swing.JPasswordField();
        jLabelNome = new javax.swing.JLabel();
        campoNomeCadastro = new javax.swing.JTextField();
        btnCadastrar2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Spotifei - Cadastro");
        setPreferredSize(new java.awt.Dimension(500, 400));
        setResizable(false);

        jLabelSpotifei2.setBackground(new java.awt.Color(0, 0, 0));
        jLabelSpotifei2.setFont(new java.awt.Font("Segoe UI Emoji", 1, 12)); // NOI18N
        jLabelSpotifei2.setForeground(new java.awt.Color(0, 255, 0));
        jLabelSpotifei2.setText("Spotifei");
        jLabelSpotifei2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabelEmailCadastro.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        jLabelEmailCadastro.setForeground(new java.awt.Color(0, 255, 0));
        jLabelEmailCadastro.setText("Email:");

        jLabelSenhaCadastro.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        jLabelSenhaCadastro.setForeground(new java.awt.Color(0, 255, 0));
        jLabelSenhaCadastro.setText("Senha:");

        campoEmailCadastro.setForeground(new java.awt.Color(0, 255, 0));
        campoEmailCadastro.setCaretColor(new java.awt.Color(0, 255, 0));
        campoEmailCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoEmailCadastroActionPerformed(evt);
            }
        });

        campoSenhaCadastro.setForeground(new java.awt.Color(0, 255, 0));
        campoSenhaCadastro.setCaretColor(new java.awt.Color(0, 255, 0));
        campoSenhaCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoSenhaCadastroActionPerformed(evt);
            }
        });

        jLabelNome.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        jLabelNome.setForeground(new java.awt.Color(0, 255, 0));
        jLabelNome.setText("Nome:");

        campoNomeCadastro.setForeground(new java.awt.Color(0, 255, 0));
        campoNomeCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoNomeCadastroActionPerformed(evt);
            }
        });

        btnCadastrar2.setBackground(new java.awt.Color(0, 0, 0));
        btnCadastrar2.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        btnCadastrar2.setForeground(new java.awt.Color(0, 255, 0));
        btnCadastrar2.setText("Cadastrar");
        btnCadastrar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrar2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnCadastrar2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabelSenhaCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(campoSenhaCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(163, 163, 163)
                            .addComponent(jLabelSpotifei2))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabelNome, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabelEmailCadastro, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(campoEmailCadastro, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                .addComponent(campoNomeCadastro)))))
                .addContainerGap(141, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelSpotifei2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNome)
                    .addComponent(campoNomeCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelEmailCadastro)
                    .addComponent(campoEmailCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSenhaCadastro)
                    .addComponent(campoSenhaCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                .addComponent(btnCadastrar2, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void campoEmailCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoEmailCadastroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoEmailCadastroActionPerformed

    private void campoSenhaCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoSenhaCadastroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoSenhaCadastroActionPerformed

    private void btnCadastrar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrar2ActionPerformed
                                                
    String nome = campoNomeCadastro.getText();
    String email = campoEmailCadastro.getText();
    String senha = new String(campoSenhaCadastro.getPassword());
    UsuarioController usuarioController = new UsuarioController();


     boolean cadastrado = usuarioController.cadastrarUsuario(nome, email, senha);
        if (cadastrado) {
            JOptionPane.showMessageDialog(this, "Cadastro realizado com sucesso!");
            new TelaLogin().setVisible(true);
            dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Erro ao cadastrar! Verifique os dados.");
        }
    }//GEN-LAST:event_btnCadastrar2ActionPerformed

    private void campoNomeCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoNomeCadastroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoNomeCadastroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrar2;
    private javax.swing.JTextField campoEmailCadastro;
    private javax.swing.JTextField campoNomeCadastro;
    private javax.swing.JPasswordField campoSenhaCadastro;
    private javax.swing.JLabel jLabelEmailCadastro;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JLabel jLabelSenhaCadastro;
    private javax.swing.JLabel jLabelSpotifei2;
    // End of variables declaration//GEN-END:variables
}
